version: '3.7'

services:
  tweet_service_postgres:
        container_name: tweet_service_db
        build:
          context: ./backend/tweet_service/postgres
          dockerfile: Dockerfile
        restart: on-failure
        environment:
          POSTGRES_PASSWORD: ${TWEET_DB_PASSWORD}
          POSTGRES_USER: ${TWEET_DB_USER}
          POSTGRES_DB: ${TWEET_DB_NAME}
        ports:
          - ${TWEET_DB_PORT}:${TWEET_DB_PORT}
          # - 5433:5433
        command: -p ${TWEET_DB_PORT}
        volumes:
        - '${TWEET_LOCAL_DATA_DIR}/postgresql:/var/lib/postgresql/data'


  tweet_service:
    container_name: tweet_api
    volumes:
      - ./backend/tweet_service:/src
    build:
      context: ./backend/tweet_service
    restart: on-failure
    ports:
      - ${TWEET_SERVICE_PORT}:${TWEET_SERVICE_PORT}
    tty: true
    depends_on:
      - tweet_service_postgres
    links:
      - tweet_service_postgres
    environment:
      - TWEET_SERVICE_PORT=${TWEET_SERVICE_PORT}
      - TWEET_DB_HOST=${TWEET_DB_HOST}
      - TWEET_DB_DRIVER=${TWEET_DB_DRIVER}
      - TWEET_DB_USER=${TWEET_DB_USER}
      - TWEET_DB_PASSWORD=${TWEET_DB_PASSWORD}
      - TWEET_DB_NAME=${TWEET_DB_NAME}
      - TWEET_DB_PORT=${TWEET_DB_PORT}

  auth_service_postgres:
      container_name: auth_service_db
      build:
        context: ./backend/auth_service/postgres
        dockerfile: Dockerfile
      restart: on-failure
      environment:
        POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
        POSTGRES_USER: ${AUTH_DB_USER}
        POSTGRES_DB: ${AUTH_DB_NAME}
      ports:
        - 5432:5432

      volumes:
      - '${AUTH_LOCAL_DATA_DIR}/postgresql:/var/lib/postgresql/data'

  authentication_service:
    container_name: auth_api
    volumes:
      - ./backend/auth_service:/app
    build:
      context: ./backend/auth_service
    restart: on-failure
    ports:
      - 8081:8081
    tty: true
    depends_on:
      - auth_service_postgres
    links:
      - auth_service_postgres
    environment:
      - AUTH_DB_HOST=${AUTH_DB_HOST}
      - AUTH_DB_DRIVER=${AUTH_DB_DRIVER}
      - AUTH_DB_PASS=${DB_PASS}
      - AUTH_DB_USER=${AUTH_DB_USER}
      - AUTH_DB_PASSWORD=${AUTH_DB_PASSWORD}
      - AUTH_DB_NAME=${AUTH_DB_NAME}
      - AUTH_DB_PORT=${AUTH_DB_PORT}
      - AUTH_API_SECRET=${AUTH_API_SECRET}
      - AUTH_TOKEN_HOUR_LIFESPAN=${AUTH_TOKEN_HOUR_LIFESPAN}


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    depends_on:
      - tweet_service
      - authentication_service
