version: '3.7'

services:
  auth_service_postgres:
      container_name: auth_service_db
      build:
        context: ./backend/auth_service/postgres
        dockerfile: Dockerfile
      restart: on-failure
      environment:
        POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
        POSTGRES_USER: ${AUTH_DB_USER}
        POSTGRES_DB: ${AUTH_DB_NAME}
      ports:
        - 5432:5432

      volumes:
      - '${AUTH_LOCAL_DATA_DIR}/postgresql:/var/lib/postgresql/data'

  authentication_service:
    container_name: auth_api
    volumes:
      - ./backend/auth_service:/app
    build:
      context: ./backend/auth_service
    restart: on-failure
    ports:
      - 8081:8081
    tty: true
    depends_on:
      - auth_service_postgres
    links:
      - auth_service_postgres
    environment:
      - AUTH_DB_HOST=${AUTH_DB_HOST}
      - AUTH_DB_DRIVER=${AUTH_DB_DRIVER}
      - DB_PASS=${DB_PASS}
      - AUTH_DB_USER=${AUTH_DB_USER}
      - AUTH_DB_PASSWORD=${AUTH_DB_PASSWORD}
      - AUTH_DB_NAME=${AUTH_DB_NAME}
      - AUTH_DB_PORT=${AUTH_DB_PORT}
      - AUTH_API_SECRET=${AUTH_API_SECRET}
      - AUTH_TOKEN_HOUR_LIFESPAN=${AUTH_TOKEN_HOUR_LIFESPAN}


  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: backend
  #   volumes:
  #     - ./backend:/src
  #     - '${LOCAL_DATA_DIR}:/src/data'
  #   ports:
  #     - 8000:8000
  #   environment:
  #     - DB_ENDPOINT=${DB_ENDPOINT}
  #     - DB_USER=${DB_USER}
  #     - DB_PASS=${DB_PASS}
  #     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #     - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
  #     - AWS_REGION_NAME=${AWS_REGION_NAME}


  #   depends_on:
  #     - development-db

  # development-db:
  #   build:
  #     context: ./postgres
  #     dockerfile: Dockerfile
  #   container_name: development-db
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASS}
  #     DB_ENDPOINT: ${DB_ENDPOINT}
  #     POSTGRES_DB: app_db

  #   volumes:
  #     - '${LOCAL_DATA_DIR}/postgresql:/var/lib/postgresql/data'

  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   container_name: nginx
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - backend
  #     - frontend

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - HOST=0.0.0.0
  #     - PORT=3000
  #     - NODE_ENV=development
  #     - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
  #     - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
  #     - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
  #   depends_on:
  #     - backend
