version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/src
      - '${LOCAL_DATA_DIR}:/src/data'
    ports:
      - 8000:8000
    environment:
      # - APP_SETTINGS=project.config.DevelopmentConfig
      - DB_ENDPOINT=development-db
      # - DATABASE_URL=postgres://postgres:postgres@development-db:5432/dev_db
      # - DATABASE_TEST_URL=postgres://postgres:postgres@development-db:5432/test_db
      # - SECRET_KEY=ZQbn05PDeA7v11
    depends_on:
      - development-db

  development-db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass

  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - api
  #     - client

  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   volumes:
  #     - './client:/usr/src/app'
  #     - '/usr/src/app/node_modules'
  #   ports:
  #     - 3008:3000
  #   environment:
  #     - NODE_ENV=development
  #     - REACT_APP_SERVICE_URL=http://localhost:8080
  #     - CHOKIDAR_USEPOLLING=true
  #   depends_on:
  #     - api
